Move things

diff --git a/util/launch-emulator b/util/launch-emulator
--- a/util/launch-emulator
+++ b/util/launch-emulator
@@ -4,38 +4,50 @@ cd "$(realpath "$(dirname "$BASH_SOURCE")")/.."
 
 pid_file=/tmp/emulator.pid
 
+log () {
+    echo "[[1;34m$0[0m] $@"
+}
+warning () {
+    log "[[1;33mWARNING[0m] $@" >&2
+}
+error () {
+    log "[[1;31mERROR[0m] $@" >&2
+    exit 1
+}
+
 print_usage () {
     cat >&2 <<- EOF
-	usage: launch-emulator WEBCAM_DEVICE [EMULATOR_ARGS ...]
+	usage: launch-emulator [WEBCAM_DEVICE] [EMULATOR_ARGS ...]
 	Launch an emulator instance
 	- Returns the emulator PID in \`/tmp/emulator.pid\`
 
 	arguments:
-	  WEBCAM_DEVICE     Path of the \`/dev/videoN\` device to use as webcam
-	  EMULATOR_ARGS     Additional arguments to pass to the emulator
+      WEBCAM_DEVICE     path of the \`/dev/videoN\` device to use as webcam (optional)
+      EMULATOR_ARGS     additional arguments to pass to the emulator (optional)
 	options:
 	  -h, --help        show this message
 	EOF
 }
 
-[[ -n "$1" ]] || {
-    print_usage
-    exit 1
-}
 case "$1" in
     -h | --help)
         print_usage
         exit
         ;;
     *)  device="$1"
-        shift
+        # Device may not be provided
+        [[ -z "$device" ]] ||
+            shift
         ;;
 esac
 
-additional_args="$@"
+emulator_args=(
+    @qrfuzz
+    "$@"
+)
 
 if [[ -f "$pid_file" ]] && ps -p $(cat "$pid_file") &> /dev/null; then
-    echo An emulator instance is already running >&2
+    warning An emulator instance is already running
     exit 0
 fi
 
@@ -57,17 +69,16 @@ which emulator &> /dev/null || {
     fi
 }
 
-# Get webcam name from emulator
-webcam=$(emulator -webcam-list 2> /dev/null | grep "$device" | grep -o 'webcam[0-9]*') || {
-    echo Android emulator is unable to find the virtual webcam >&2
-    exit 1
+[[ -z "$device" ]] || {
+    # Get webcam name from emulator
+    webcam=$(emulator -webcam-list 2> /dev/null | grep "$device" | grep -o 'webcam[0-9]*') ||
+        error Android emulator could not find a webcam on \`$device\`
+    emulator_args+=(-camera-back "$webcam")
 }
 
 # Launch the emulator
 emulator &> /tmp/emulator.log \
-    @qrfuzz \
-    -camera-back $webcam \
-    $additional_args \
+    "${emulator_args[@]}" \
     &
 
 # Save the emulator PID
