Errors

diff --git a/setup/android-sdk b/setup/android-sdk
--- a/setup/android-sdk
+++ b/setup/android-sdk
@@ -6,7 +6,7 @@ log () {
 }
 
 error () {
-    echo "[[1;31mERROR[0m] $@" >&2
+    log "[[1;31mERROR[0m] $@" >&2
     exit 1
 }
 
@@ -69,7 +69,7 @@ esac
 }
 
 which sdkmanager &> /dev/null ||
-    export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"
+    export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"
 
 # Check that Java Runtime is installed and is the correct version (>= 17)
 sdkmanager --version &> /dev/null || {
diff --git a/setup/ffmpeg b/setup/ffmpeg
--- a/setup/ffmpeg
+++ b/setup/ffmpeg
@@ -1,20 +1,27 @@
 #!/bin/bash
 set -e
 
+log () {
+    echo "[[1;34m$0[0m] $@"
+}
+
 error () {
-    echo "[[1;31mERROR[0m] $@" >&2
+    log "[[1;31mERROR[0m] $@" >&2
     exit 1
 }
 
 # Debian-based
 if which apt &> /dev/null; then
+    log 'Running: sudo apt update && sudo apt install ffmpeg'
     sudo apt update
     sudo apt install ffmpeg
 # Arch-based
 elif which pacman &> /dev/null; then
+    log 'Running: sudo pacman -S ffmpeg'
     sudo pacman -S ffmpeg
 # RHEL-based
 elif which dnf &> /dev/null; then
+    log 'Running: sudo dnf install ffmpeg'
     sudo dnf install ffmpeg
 else
     error No supported package manager was found
